[ui]
hideTopBar = true

[server]
enableStaticServing = true

[theme]
primaryColor = "#67597A"       # Deep purple for primary actions
backgroundColor = "#F4F7BE"    # Light cream for background
secondaryBackgroundColor = "#E5F77D"  # Bright lime for secondary backgrounds
textColor = "#757761"          # Olive gray for text
font = "serif"                 # Using serif font family